// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmL9EYtl6wPQPKnP6hc3ZFujlNvTwqtcI',
    appId: '1:79978912572:web:80d362e677fb10b8d01c39',
    messagingSenderId: '79978912572',
    projectId: 'pawscare-7e2fe',
    authDomain: 'pawscare-7e2fe.firebaseapp.com',
    storageBucket: 'pawscare-7e2fe.appspot.com',
    measurementId: 'G-3D6D0F6MR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPtLcbLmnbYAZ75ZTUayyuF0zLwb-W9Pw',
    appId: '1:79978912572:android:ffc11e4e5389cbedd01c39',
    messagingSenderId: '79978912572',
    projectId: 'pawscare-7e2fe',
    storageBucket: 'pawscare-7e2fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-GlsPRV5Xj74FmL5X6_74G16O6N0FfI',
    appId: '1:79978912572:ios:1566fb442ca55766d01c39',
    messagingSenderId: '79978912572',
    projectId: 'pawscare-7e2fe',
    storageBucket: 'pawscare-7e2fe.appspot.com',
    iosBundleId: 'com.example.pawscare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-GlsPRV5Xj74FmL5X6_74G16O6N0FfI',
    appId: '1:79978912572:ios:98099664999fea42d01c39',
    messagingSenderId: '79978912572',
    projectId: 'pawscare-7e2fe',
    storageBucket: 'pawscare-7e2fe.appspot.com',
    iosBundleId: 'com.example.pawscare.RunnerTests',
  );
}
